server:
  port: 8001
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: user-before
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true #优先使用服务ip进行注册
           #openFeign超时控制  为了更好节省内存资源 提搞用户的体验
    openfeign:
      client:
        config:
          default:
            #连接超时时间 3秒
            connect-timeout: 3000
            #读取数据的时间
            read-timeout: 3000



# ========================zipkin===================
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 #采样率默认为0.1(0.1就是10次只能有一次被记录下来)，值越大收集越及时。
